# Generated by Django 5.0.3 on 2024-04-01 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepg', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='teacher',
        ),
    ]
