# Generated by Django 5.0.3 on 2024-04-01 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepg', '0005_alter_certificate_image_alter_certificate_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='image',
            field=models.ImageField(null=True, upload_to='certificates/'),
        ),
    ]
