# Generated by Django 5.0.3 on 2024-04-04 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepg', '0006_alter_certificate_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('points', models.IntegerField(default=0)),
                ('limit', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='batch',
            field=models.IntegerField(choices=[('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], default='12'),
        ),
        migrations.AddField(
            model_name='student',
            name='regno',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='batch',
            field=models.IntegerField(choices=[('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], default='12'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='homepg.activity'),
        ),
    ]
