# Generated by Django 5.0.3 on 2024-04-30 15:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepg', '0013_alter_student_regno_alter_studentrequest_regno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='activity',
            name='limit',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='points',
        ),
        migrations.AddField(
            model_name='activity',
            name='approved_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activity',
            name='certificate',
            field=models.FileField(blank=True, default=None, upload_to='certificates/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AddField(
            model_name='activity',
            name='end_date',
            field=models.DateField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='activity',
            name='points_obtained',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='activity',
            name='start_date',
            field=models.DateField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='activity',
            name='student',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='homepg.student'),
        ),
        migrations.AddField(
            model_name='activity',
            name='category',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='homepg.category'),
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('max', models.IntegerField()),
                ('has_levels', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepg.category')),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('points_awarded', models.IntegerField(default=0)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepg.subcategory')),
            ],
        ),
        migrations.DeleteModel(
            name='Certificate',
        ),
    ]
