# Generated by Django 5.0.3 on 2024-04-30 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepg', '0014_category_remove_activity_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='additional',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='additional_points',
            field=models.IntegerField(default=0),
        ),
    ]
