# Generated by Django 5.0.3 on 2024-04-30 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepg', '0018_remove_activity_subcategory_activity_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='participation_level',
            field=models.BooleanField(default=False),
        ),
    ]
