# Generated by Django 5.0.3 on 2024-05-01 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepg', '0021_remove_level_level_level_levelname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='certificate',
            field=models.FileField(blank=True, default=None, upload_to='certificates/'),
        ),
    ]
