# Generated by Django 5.0.3 on 2024-04-01 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepg', '0003_student_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='description',
        ),
        migrations.AddField(
            model_name='certificate',
            name='image',
            field=models.ImageField(null=True, upload_to='Certificates'),
        ),
    ]
