# Generated by Django 5.0.3 on 2024-04-10 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepg', '0007_activity_student_batch_student_regno_teacher_batch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='batch',
            field=models.IntegerField(choices=[('9', '9'), ('10', '10'), ('11', '11'), ('12-a', '12-a'), ('12-b', '12-b')], default='12'),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='batch',
            field=models.IntegerField(choices=[('9', '9'), ('10', '10'), ('11', '11'), ('12-a', '12-a'), ('12-b', '12-b')], default='12'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
