# Generated by Django 5.0.3 on 2024-04-10 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepg', '0011_alter_student_batch_alter_teacher_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='StudentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('regno', models.CharField(max_length=20, null=True)),
                ('batch', models.CharField(choices=[('9', '9'), ('10', '10'), ('11', '11'), ('12-a', '12-a'), ('12-b', '12-b')], default='9', max_length=10)),
                ('points', models.IntegerField(default=0)),
                ('teacher', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='homepg.teacher')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
