# Generated by Django 5.0.3 on 2024-04-30 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepg', '0015_subcategory_additional_subcategory_additional_points'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='additional_points',
            new_name='additional_max',
        ),
    ]
