# Generated by Django 5.0.3 on 2024-04-30 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepg', '0016_rename_additional_points_subcategory_additional_max'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='category',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='additional_max',
        ),
        migrations.AddField(
            model_name='activity',
            name='subcategory',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='homepg.subcategory'),
        ),
    ]
