# Generated by Django 5.0.3 on 2024-04-30 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepg', '0017_remove_activity_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='activity',
            name='level',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='homepg.level'),
        ),
        migrations.AlterField(
            model_name='level',
            name='level',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1),
        ),
    ]
