# Generated by Django 5.0.3 on 2024-04-30 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepg', '0019_subcategory_participation_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='participation_level',
        ),
    ]
