# Generated by Django 5.0.3 on 2024-05-01 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepg', '0020_remove_subcategory_participation_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='level',
        ),
        migrations.AddField(
            model_name='level',
            name='levelname',
            field=models.CharField(default='', max_length=100),
        ),
    ]
