# Generated by Django 5.0.3 on 2024-05-08 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepg', '0025_achievement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='level',
        ),
        migrations.AddField(
            model_name='achievement',
            name='level',
            field=models.ManyToManyField(related_name='achievements', to='homepg.level'),
        ),
    ]
