# Generated by Django 5.0.3 on 2024-05-08 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepg', '0026_remove_achievement_level_achievement_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='achievement',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='homepg.achievement'),
        ),
        migrations.AddField(
            model_name='activity',
            name='additional_obtained',
            field=models.IntegerField(default=0),
        ),
    ]
